### PR TITLE
Added angular files

### PR DESCRIPTION
**Pull request by MsMarini**

### CODE REVIEW

**Comment by flennaja** [comment]
The files look good, but can you create a new directory/folder called AppSettingsManagerUi and put all of these in there? We have to put the API/BFF/UI all in the same git repo so we're gonna want to keep them separate.

**Review by n898c — APPROVED** [review]

**Comment by arushwolf** [comment]
Moved the Angular files into AppSettingsManagerUI folder.

**Review by arushwolf — APPROVED** [review]
Approving this as the needed changes have been made.

**Comment by flennaja** [comment]
> Moved the Angular files into AppSettingsManagerUI folder.

@arushwolf It looks like the /src folder is still outside of the AppSettingsManagerUi folder

**Comment by arushwolf** [comment]
Sorry, fixed that.

**Review by flennaja — APPROVED** [review]

**Comment by arushwolf** [comment]
I am going to pop into the UI branch and merger it to main to get this outta the way.

**Pull request merged**
